site_name: kintone WeChat Mini Program SDK
site_description: The SDK of kintone REST API client on WeChat Mini Program

repo_url: https://github.com/kintone/kintone-wechat-miniprogram-sdk
site_url: https://kintone.github.io/kintone-wechat-miniprogram-sdk/
theme:
  name: 'material'
  custom_dir: 'docs/custom_theme'
  favicon: favicon.ico
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'
  logo:
    icon: 'cloud'
extra_javascript:
  - 'asset/js/extra.js'
extra_css:
  - 'asset/style/extra.css'
extra:
  version: 0.1.0
markdown_extensions:
  - admonition

nav:
- Home: index.md
- Getting Started:
  - Quickstart: getting-started/quickstart.md
- Reference:
  - Authentication: reference/authentication.md
  - Connection: reference/connection.md
  - Record: reference/record.md
  - Record Cursor: reference/record-cursor.md
  - Bulk Request: reference/bulk-request.md
  - App: reference/app.md
  - Kintone APIException: reference/kintone-api-exception.md
  - File: reference/file.md
